main_app/urls.py
from django.conf.urls import url
from . import views

app_name='main_app'
urlpatterns = [
    url(r'^$', views.welcome, name='welcome'),
    url(r'^insa', views.insa, name='insa'),
    url(r'^consent/', views.consent, name='consent'),
    url(r'^demographics/', views.demographics, name='demographics'),
    url(r'^test/', views.test, name='test'),
    url(r'^test_submission/', views.test_submission, name='test_submission'),
    url(r'^faces_intro/', views.faces_intro, name='faces_intro'),
    url(r'^faces/', views.faces, name='faces'),
    url(r'^get_analysed_text/', views.get_analysed_text, name='get_analysed_text'),
    url(r'^get_ans_to_qs/', views.get_ans_to_qs, name='get_ans_to_qs'),
    url(r'^log_in/', views.log_in, name='log_in'),
    url(r'^debriefing/', views.debriefing, name='debriefing'),
    url(r'^no_consent_debriefing/', views.no_consent_debriefing, name='no_consent_debriefing'),
    url(r'^logout/$', views.logout_view, name='logout_view'),
    url(r'^bibo/', views.bibo, name='bibo'),
]

the_experiment/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
import pycountry
import os
import csv
from django.conf import settings
from django.contrib.auth.models import User

class Participant(models.Model):
    person = models.ForeignKey(User, null=True)
    country_options = sorted([(country.alpha_2, country.name) for country in list(pycountry.countries)], key=lambda c: c[1])
    with open(os.path.join(settings.BASE_DIR, 'main_app/static/main_app/mery_imgs/Languages.csv'), 'r') as f:
        reader = csv.reader(f)
        pre_language_options = [(row[1], row[0]) for row in reader] + [('CC', 'Chinese (Cantonese)'), ('OO', ' Other')]
        language_options = sorted(pre_language_options, key=lambda c: c[1])
    age_options = [('18', '18 - 24'), ('25', '25 - 34'), ('35', '35 - 44'), ('45', '45 - 54'), ('55', '55 - 64'), ('65', '65+')]
    living_now_options = [('yes', 'yes'), ('no', 'no')]
    years_in_esc_options = [('0', 'never'), ('1', '1 - 12 months'), ('2', '1 - 2 years'), ('3', '3 - 4'), ('5', 'more than 5 years')]
    english_level_options = [('6', 'high advanced'), ('5', 'low advanced'), ('4', 'high intermediate'), ('3', 'low intermediate'), ('2', 'high beginner'), ('1', 'low beginner')]
    living_now_choices = [(True, 'Yes'), (False, 'No')]
    country = models.CharField(max_length=2, choices=country_options, blank=False, null=True)
    language = models.CharField(max_length=2, choices=language_options, blank=False, null=True)
    age = models.CharField(max_length=2, choices=age_options, blank=False, null=True)
    living_now = models.CharField(max_length=3, choices=living_now_choices, blank=True, null=True)
    years_in_esc = models.CharField(max_length=1, choices=years_in_esc_options, blank=True, null=True)
    english_level = models.CharField(max_length=1, choices=english_level_options, blank=True, null=True)

class NoConsent(models.Model):
    reason = models.CharField(max_length=500, blank=True)
    when = models.DateTimeField(auto_now_add=True)

class EnglishTest(models.Model):
    person = models.ForeignKey(User)
    answers = models.CharField(max_length=15)

class Sentence(models.Model):
    person = models.ForeignKey(User, null=True)
    s1 = models.CharField(max_length=300, blank=True, null=True, default='')
    s2 = models.CharField(max_length=300, blank=True, null=True, default='')
    s3 = models.CharField(max_length=300, blank=True, null=True, default='')
    s3_expression = models.CharField(max_length=1, blank=True, null=True, default=None)
    s3_reason = models.CharField(max_length=1, blank=True, null=True, default=None)
    s4 = models.CharField(max_length=300, blank=True, null=True, default='')
    s5 = models.CharField(max_length=300, blank=True, null=True, default='')
    s5_expression_change = models.CharField(max_length=1, blank=True, null=True, default=None)
    s6 = models.CharField(max_length=300, blank=True, null=True, default='')
    s6_expression_change = models.CharField(max_length=1, blank=True, null=True, default=None)

main_app/forms.py
from django import forms
from .models import Participant
from django.forms import RadioSelect, Select
from django.utils.safestring import mark_safe


class AllParticipantForm(forms.ModelForm):

    class Meta:
        model = Participant
        fields = ['country', 'age', 'language']
        labels = {
            'country': mark_safe("Where are you from?<br/><p>"),
            'language': mark_safe("What is your native language?<br/><p>"),
            'age': mark_safe("How old are you?<br/><p>"),
        }

class NonNativeParticipantForm(forms.ModelForm):

    class Meta:
        model = Participant
        fields = ['living_now', 'years_in_esc', 'english_level']
        labels = {
            'living_now': mark_safe("Do you live in an English speaking country now?<br/><p>"),
            'years_in_esc': mark_safe("How long have you lived in an English speaking country?<br/><p>"),
            'english_level': mark_safe("What is your English level?<br/><p>"),
        }

main_app/views.py
from django.shortcuts import render, redirect
import random
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from .models import Participant, NoConsent, EnglishTest, Sentence
from django.http import JsonResponse
from .forms import AllParticipantForm, NonNativeParticipantForm
from django.contrib.auth.decorators import login_required
import language_check

tool = language_check.LanguageTool('en-US')

def all_done(request):
    all_done = False
    try: 
        user = request.user
        try: 
            sentence_object = Sentence.objects.get(person=user)
            if sentence_object.s6 != '':
                all_done = True
        except:
            pass
    except:
        pass
    return all_done

def welcome(request):
    a_d = all_done(request)
    context = {
        "a_d": a_d,
    }
    return render(request, 'welcome.html', context)

def insa(request):
    a_d = all_done(request)
    context = {
        "a_d": a_d,
    }
    return render(request, 'insa.html', context)

def consent(request):
    # import code
    # code.interact(local=locals())
    a_d = all_done(request)
    if request.method == "POST":
        if "reason for leaving" in request.POST:
            given_reason = request.POST['typed_reason']
            NoConsent.objects.create(reason=given_reason)
            return redirect('main_app:no_consent_debriefing')

    context = {
        "a_d": a_d,
    }
    return render(request, 'consent.html', context)

def create_username(request, name):
    u = User.objects.create_user(name, email=None)
    login(request, u)
    user = u.username
    return user

def log_in(request):
    all_usernames = [i.username for i in User.objects.all()]
    unique_name = False
    while unique_name != True:
        name = random.randint(1, 999999)
        if name not in all_usernames:
            user = create_username(request, name)
            unique_name = True
    response_data = {'user': user }
    return JsonResponse(response_data) 

@login_required(login_url='/')
def demographics(request):
    # import code
    # code.interact(local=locals())
    a_d = all_done(request)
    user = request.user
    if request.method == 'POST':
        a_p_form = AllParticipantForm(request.POST)
        p = a_p_form.save(commit=False)
        if request.POST['language'] != 'EN':
            p.living_now = request.POST['living_now']
            p.years_in_esc = request.POST['years_in_esc']
            p.english_level = request.POST['english_level']
        p.person = user
        p.save()
        return redirect('main_app:test')
    a_p_form = AllParticipantForm(label_suffix='')
    n_n_p_form = NonNativeParticipantForm(label_suffix='')
    username = user.username
    context = {
        "a_d": a_d,
        'a_p_form': a_p_form,
        'n_n_p_form': n_n_p_form,
        'username': username,
    }
    return render(request, 'demographics.html', context)

@login_required(login_url='/')
def test(request):
    # import code
    # code.interact(local=locals())
    a_d = all_done(request)
    user = request.user
    person = Participant.objects.get(person=user)
    context = {
        "a_d": a_d,
    }
    return render(request, 'test.html', context)

def test_submission(request):
    user = request.user
    answers = request.GET['answers']
    test_object = EnglishTest.objects.create(person=user, answers=answers)
    response_data = {

    }
    return JsonResponse(response_data)

@login_required(login_url='/')
def faces_intro(request):
    a_d = all_done(request)
    context = {
        "a_d": a_d,
    }
    return render(request, 'faces_intro.html', context)

@login_required(login_url='/')
def faces(request):
    a_d = all_done(request)
    user = request.user
    sentence = 0
    try:
        sentences_object = Sentence.objects.get(person=user)
        if sentences_object.s6 != '':
            return redirect('main_app:debriefing')
        elif sentences_object.s2 == '':
            sentence = 1
        elif sentences_object.s3 == '':
            sentence = 2
        elif sentences_object.s4 == '':
            sentence = 3
        elif sentences_object.s5 == '':
            sentence = 4
        elif sentences_object.s6 == '':
            sentence = 5
    except Sentence.DoesNotExist:
        sentence = 0
    context = {
        "a_d": a_d,
        "sentence": str(sentence),
    }
    return render(request, 'faces.html', context)

def get_analysed_text(request):
    # import code
    # code.interact(local=locals())
    user = request.user
    sent_no = int(request.GET['sentence_no'])
    get_text = request.GET['sentence'].capitalize()
    matches = tool.check(get_text)
    sent_len = len(get_text.split())
    good_sentence = True
    if sent_len < 3 or len(matches) > sent_len // 2:
        good_sentence = False
    else:
        if sent_no == 0:
            try:
                sentences_object = Sentence.objects.get(person=user)
                sentences_object.delete()
                sentences_object = Sentence.objects.create(person=user, s1="REPEAT: " + get_text)
            except Sentence.DoesNotExist:
                sentences_object = Sentence.objects.create(person=user, s1=get_text, s2='', s3='', s4='', s5='', s6='')
        else: 
            sentences_object = Sentence.objects.get(person=user);
            if sent_no == 1:
                sentences_object.s2 = get_text
            elif sent_no == 2:
                sentences_object.s3 = get_text
            elif sent_no == 3:
                sentences_object.s4 = get_text
            elif sent_no == 4:
                sentences_object.s5 = get_text
            elif sent_no == 5:
                sentences_object.s6 = get_text
            sentences_object.save()
    response_data = {
        'sent_len': sent_len,
        'good_sentence': good_sentence,
    }
    return JsonResponse(response_data)

def get_ans_to_qs(request):
    user = request.user
    sent_no = request.GET['sentence_no']
    try:
        sentence_object = Sentence.objects.get(person=user)
        if sent_no == '3':
            sentence_object.s3_expression = request.GET['ans31']
            sentence_object.s3_reason = request.GET['ans32']
        elif sent_no == '5':
            sentence_object.s5_expression_change = request.GET['ans51']
        elif sent_no == '6':
            sentence_object.s6_expression_change = request.GET['ans61']
        sentence_object.save()
    except Sentence.DoesNotExist:
        pass
    return JsonResponse({"success": 'success'})




@login_required(login_url='/')
def debriefing(request):
    context = {

    }
    return render(request, 'debriefing.html', context)

def no_consent_debriefing(request):
    context = {

    }
    return render(request, 'no_consent_debriefing.html', context)

def logout_view(request):
    logout(request)
    return redirect('main_app:welcome')


def bibo(request):
    context = {

    }
    return render(request, 'bibo.html', context)

main_app/templates/main_app/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'main_app/stylesheets/base.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="/static/main_app/javascript/base.js?{% now "U" %}"></script>
        {% block cssANDjs%}
        {% endblock %}
    </head>
    <body>
        <div class="whole-background"></div>
        <div class="navbar">
        <img src="/static/main_app/mery_imgs/adapt_logo.png" id="adapt-logo">
        <div id="title">
            <h3>Emotion & Language</h3>
        </div>
<!--         {% if user != None %}
            <a href="{% url 'main_app:logout_view' %}"><button type='button' class='btn btn-warning'>{{ username }}</button></a>
        {% endif %} -->
        <img src="/static/main_app/mery_imgs/ucd_logo.png" id="ucd-logo">
    </div>
    <div id='backgroundDiv'>
        {% block content %}
        {% endblock %}
    </div>
    </body>
</html>

main_app/templates/main_app/bibo.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <style>
            h3 {
                text-align: center;
            }
            .main-div {
                width: 600px;
                height: 600px; 
                margin-left:auto; 
                margin-right: auto;
            }
            .bibo-bck {
                height: 320px;
                width: 400px;
                margin-left: auto;
                margin-right: auto;
            }
            .bibo-jpg {
                border: 2px black solid;
                background-repeat: no-repeat;
                height: 320px;
                width: 400px;
                background-position: 0px 0px;
                display: inline-block;
                background-image: url(/static/main_app/mery_imgs/mery_bibo.jpg);
            }
        </style>
        <script>

        </script>
    </head>
    <body>
        <div class="main-div">
            <h3>bibo</h3>
            <div class='bibo-bck'><div class="bibo-jpg"></div></div>
        </div>
    </body>
</html>

main_app/templates/main_app/consent.html
{% extends "base.html" %}
{% load static %}
{% block cssANDjs %}
    <link rel="stylesheet" href="/static/main_app/stylesheets/consent.css?{% now "U" %}">
    <script src="/static/main_app/javascript/consent.js?{% now "U" %}"></script>
{% endblock %}
{% block content %}
    {% if not a_d %}
        <p>In this experiment, you will answer questions, type sentences and watch Mery's facial expressions.</p>
        <p>It should take 10 minutes to complete the following 5 sections:</p>
        {% include 'experiment_map.html' %}
        <p>Before beginning, please carefully read the Information Sheet and check all the boxes on the Consent Form.</p>
        <p class="supplementaryPTag">(If you do not wish to consent or do not want to provide the information requested below, please click 'I do not agree')</p>
        <div class="information-sheet">
            <p class="information-sheet-title">Information Sheet </p>
            <p class="information-sheet-b"><span style="font-weight: bold;">Title:</span>&nbsp;&nbsp;&nbsp; An investigation into the response of native and non-native speakers to change in facial expression of a 3D avatar to their typed sentences. </p>
            <p class="information-sheet-b"><span style="font-weight: bold;">Topic:</span>&nbsp;&nbsp;&nbsp; Second Language Acquisition, Computational Linguistics, Multimodal Communication</p>
            <p class="information-sheet-b"><span style="font-weight: bold;">Institution:</span>&nbsp;&nbsp;&nbsp; UCD Computer Science</p>
            <p class="information-sheet-b" style="margin-bottom: -20px;"><span style="font-weight: bold;">Researcher:</span>&nbsp;&nbsp;&nbsp; John Sloan </p>
            <p>&nbsp;</p>
            <p class="information-sheet-pb"> What is this research about? </p>
            <p class="information-sheet-p">I am studying language learning and emotions. I want to understand the difference between how language learners and native speakers feel when they see different facial expressions in a 3D avatar.</p>

            <p class="information-sheet-pb">Why are you doing this research? </p>
            <p class="information-sheet-p"> I believe facial expressions are a very important means of non-verbal communication. I want to understand what language learners think when they see different expressions and use this to help people acquire languages.</p>

            <p class="information-sheet-pb"> Why have I been invited to take part? </p>
            <p class="information-sheet-p">This study is open to all native English speakers and non-native English learners of intermediate ability and up.</p>

            <p class="information-sheet-pb">What will happen if I decide to take part in this research study? </p>
            <p class="information-sheet-p"> You will take a 15-minute quiz which has 2 sections: first, you will answer some questionson emotion & language; and second, you will type 6 sentences while you can see the facial expressions of an avatar.</p>

            <p class="information-sheet-pb"> How will the data be used? </p>
            <p class="information-sheet-p">I will use your answers from the questions to understand your English ability and what you think of the avatar’s expressions. I will use the sentences you typed on computer to understand how you change your language production after seeing various expressions.

            <p class="information-sheet-pb"> How will you protect my privacy? </p>
            <p class="information-sheet-p"> This study is anonymous. You should not enter your real name or the names of others while taking part.</p>

            <p class="information-sheet-pb">How is this research funded? </p>
            <p class="information-sheet-p">This project is partly funded through the ADAPT centre. ADAPT reviews papers in advance of submission to conferences/journals in case there are any opportunities to protect/commercialise the research. </p>

            <p class="information-sheet-pb">What are the benefits of taking part in this research study? </p>
            <p class="information-sheet-p">You will be able to practice your English. You will interact with an avatar who responds to your sentences.</p>

            <p class="information-sheet-pb">What are the risks of taking part in this research study? </p>
            <p class="information-sheet-p">If you see negative expressions from the avatar you may feel bad. </p>

            <p class="information-sheet-pb">Can I change my mind at any stage and withdraw from the study? </p>
            <p class="information-sheet-p">Yes. You can change your mind anytime and withdraw with no disadvantage. </p>

            <p class="information-sheet-pb">Has this research project received ethical approval? </p>
            <p class="information-sheet-p">Yes. Approval from the UCD Human Research Ethics comittee was granted on 25/01/2017.</p>

            <p class="information-sheet-pb">How will I find out what happens with this project? </p>
            <p class="information-sheet-p">You can email - john.sloan.1@ucdconnect.ie or phone - 00447470180188. </p>
        </div>
        <div class="consent-form">
            <div class="why-not">
                <div class="x-box"></div>
                <p class='why-not-q'>Could you tell us why you do not agree to do this experiment?</p>
                <form method="post">
                    {% csrf_token %}
                    <textarea type="input" id="why-not-text" name="typed_reason" rows='3' cols='50'></textarea>
                    <input class="btn btn-primary" id="whyNotTxtBtn" type='submit' name="reason for leaving" value="send">
                </form>
            </div>
            <p class="information-sheet-title">Consent Form</p>
            <div class="warning-div">
                <h5 class="warning">Please select all boxes. <span class="option-refuse">(If you are unable to select all boxes, please click the 'I do not agree' button and provide an explanation.)</span></h5>
            </div>
            <form class="checkboxes-form">
                <input type="checkbox" class="consent_check" name="q1" value="yes">I am over 18 years old.<br>
                <input type="checkbox" class="consent_check" name="q2" value="yes">I have read the information sheet and understand the purpose and content of this study.<br>
                <input type="checkbox" class="consent_check" name="q2" value="yes">I understand that I will answer English questions.<br>
                <input type="checkbox" class="consent_check" name="q3" value="yes">I understand that I will write English sentences.<br>
                <input type="checkbox" class="consent_check" name="q4" value="yes">I understand that I may see positive and negative expressions.<br>
                <input type="checkbox" class="consent_check" name="q5" value="yes">I understand that I can stop this experiment at any time.<br>
                <input type="checkbox" class="consent_check" name="q6" value="yes">I understand that my answers and sentences can be used in the publication of higher education....</br>
                <input type="checkbox" class="consent_check" name="q2" value="yes">I consent to taking part in this study.<br>
            </form>
            <div class="agree-buttons">
                <button type="button" class="btn btn-danger" name="start" value="No Consent" id="noBtn">I do not agree</button>
                <button type="button" class="btn btn-success" name="start" value="Let's begin" id="yesBtn">I agree</button>
            </div>
        </div>
    {% else %}
        <p>you have already completed this section</p>
        <a href="{% url 'main_app:welcome' %}"><button class="btn btn-success" style="float:right;">Homepage</button></a>
    {% endif %}
{% endblock %}

main_app/templates/main_app/debriefing.html
{% extends "base.html" %}
{% load static %}
{% block cssANDjs %}
    <link rel="stylesheet" href="/static/main_app/stylesheets/debriefing.css?{% now "U" %}">
{% endblock %}
{% block content %}
{% include 'progression.html' %}
<style>
    #ballOne, #ballTwo, #ballThree, #ballFour {
        background-color: green;
    }
    #lineOneTwo, #lineTwoThree, #lineThreeFour, #lineFourFive{
        background-color: green;
    }
    #ballFive{
        background-color: #86ff80;
        width: 50px;
        height: 50px;
        font-size: 28px;
        font-weight: bold;
        border: 2px solid green;
        padding-top: 3px;
        margin-top: -10px;
        margin-left: 710px;
    }
</style>
<div class="top-buffer">Finish</div>
<p>Thank you for your participation!</p>
<p>If you have any questions about this, or future experiments, please contact us at:</p> 
<p style="width: 200px;margin-left:auto;margin-right:auto;"><strong><u style="width: 200px;margin-left:auto;margin-right:auto;">john.sloan.1@ucdconnect.ie</u><strong></p>
<a href="{% url 'main_app:welcome' %}"><button class="btn btn-success" style="float:right;">Homepage</button></a>
{% endblock %}

main_app/templates/main_app/demographics.html
{% extends "base.html" %}
{% load static %}
{% block cssANDjs %}
    <link rel="stylesheet" href="/static/main_app/stylesheets/demographics.css?{% now "U" %}">
    <script src="/static/main_app/javascript/demographics.js?{% now "U" %}"></script>
{% endblock %}
{% block content %}
    {% if not a_d %}
        {% include 'progression.html' %}
        <style>
            #ballOne {
                background-color: #86ff80;
                width: 50px;
                height: 50px;
                font-size: 28px;
                font-weight: bold;
                border: 2px solid green;
                padding-top: 3px;
                margin-top: -10px;
                margin-left: -10px;
            }
        </style>
            <div class="top-buffer">1. About You</div>
            <form method="post">{% csrf_token %}
                <p>Please provide the following information about yourself:</p><br>
                <div class="p_form">
                    {{ a_p_form.as_p }}

                </div>
                <div class="n_n_p_form">
                    {{ n_n_p_form.as_p }}
                </div>
                <input type="submit" id="submitDemBtn" name="submit button" class="btn btn-success" value="submit" disabled>
            </form>
    {% else %}
        <p>you have already completed this section</p>
        <a href="{% url 'main_app:welcome' %}"><button class="btn btn-success" style="float:right;">Homepage</button></a>
    {% endif %}
{% endblock %}

main_app/templates/main_app/experiment_map.html
<style>
    #progression {
        height: 250px;
        width: 30px;
        margin-left: 20px;
    }
    .prog-ball {
        border-radius: 100%;
        width: 30px;
        height: 30px;
        background-color: #072a70;
        position: absolute;
        z-index: 2;
        color: white;
        text-align: center;
        padding-top: 4px;
        font-size: 16px;
    }
    #ballOne {
        position: absolute;
    }
    #ballTwo {
        position: absolute;
        margin-top: 50px;
    }
    #ballThree {
        position: absolute;
        margin-top: 100px;
    }
    #ballFour {
        position: absolute;
        margin-top: 150px;
    }
    #ballFive {
        position: absolute;
        margin-top: 200px;
    }
    .prog-line {
        height: 50px;
        width: 4px;
        background-color: #072a70;
        position: absolute;
        margin-top: 0px;
        margin-left: 13px;
        z-index: 1;
    }
    #lineOneTwo {
        margin-top: 15px;
    }
    #lineTwoThree {
        margin-top: 65px;
    }
    #lineThreeFour {
        margin-top: 115px;
    }
    #lineFourFive {
        margin-top: 165px;
    }
    #progressionText {
        position: absolute;
        margin-top: -248px;
        margin-left: 70px;
        font-weight: bold;
    }
    p {
        padding-bottom: 15px;
    }
</style>

<div id="progression">
    <div class="prog-ball" id='ballOne'>1</div>
    <div class="prog-line" id="lineOneTwo"></div>
    <div class="prog-ball" id='ballTwo'>2</div>
    <div class="prog-line" id="lineTwoThree"></div>
    <div class="prog-ball" id='ballThree'>3</div>
    <div class="prog-line" id="lineThreeFour"></div>
    <div class="prog-ball" id='ballFour'>4</div>
    <div class="prog-line" id="lineFourFive"></div>
    <div class="prog-ball" id='ballFive'>5</div>
</div>
<div id="progressionText">
    <p>About You</p>
    <p>Emotion Questions</p>
    <p>Practice with Mery</p>
    <p>Write with Mery</p>
    <p>Finish</p>
</div>

main_app/templates/main_app/faces_intro.html
{% extends "base.html" %}
{% load static %}
{% block cssANDjs %}
    <link rel="stylesheet" href="/static/main_app/stylesheets/faces_intro.css?{% now "U" %}">
    <script src="/static/main_app/javascript/faces_intro.js?{% now "U" %}"></script>
{% endblock %}
{% block content %}
    {% if not a_d %}
        {% include 'progression.html' %}
        <style>
            #ballOne, #ballTwo {
                background-color: green;
            }
            #lineOneTwo, #lineTwoThree{
                background-color: green;
            }
            #ballThree {
                background-color: #86ff80;
                width: 50px;
                height: 50px;
                font-size: 28px;
                font-weight: bold;
                border: 2px solid green;
                padding-top: 3px;
                margin-top: -10px;
                margin-left: 350px;
            }
        </style>
        <div class="body-section">
            <div class="top-buffer">Practice with Mery</div>
        <!--     <div class="mery-img-2"><div> -->
            <div class="mery-sprite"></div>
                <div class="intro-text">
                    <p>In this section you will send <Strong>2</strong> sentences to Mery.</p>
                    <p>Because this is practice, we will give you the 2 sentences to send.</p>
                    <p>You must write and send the sentences one-by-one.</p>
                    <button type="button" class="btn btn-primary" id="showQuestionButton">next</button>
                </div>
                <div class="questionbox">
                    <p><strong>Tell Mery about your best friend.</strong><br> <span class="sents-no">(2 sentences)</span></p>
                </div>
                <div class="textbox">
                    <p class="sents-no">Please write this 1st sentence in the textbox below:</p><br>
                    <p class="quote"><i>My best friend is probably the boy who moved in next door to me when I was about 6 years old.</i></p>
                    <textarea id="myTextBox" rows="4" cols="50">My best friend is probably the boy who moved in next </textarea>
                    <button type="button" class="btn btn-primary" id="sendTextButton1">send</button>
                </div>
                <div class="sentenceBox"></div>
                <div class="explanationText">
                    <p>Excellent! You can see Mery's expression <strong>changed</strong>.<p>
                    <p>Let's send the second sentence.</p>
                    <button type="button" class="btn btn-primary" id="showSentence2Button">next</button>
                </div>
                <div class="textbox2">
                    <p class="remove">Please write this 2nd sentence in the textbox below:</p><br>
                    <p class="remove quote"><i>He is tall and kind.</i></p>
                    <textarea id="myTextBox2" rows="4" cols="50" autofocus></textarea>
                    <button type="button" class="btn btn-primary" id="sendTextButton2">send</button>
                </div>
                <div class="explanationText2">
                    <p>This time, Mery's expression <strong>stayed the same</strong>.<p>
                    <p>Ok, lets begin the real experiment.</p>
                    <button type="button" id="toFacesBtn" class="btn btn-primary">start</button>
                </div>
            </div>
        </div>
    {% else %}
        <p>you have already completed this section</p>
        <a href="{% url 'main_app:welcome' %}"><button class="btn btn-success" style="float:right;">Homepage</button></a>
    {% endif %}
{% endblock %}

main_app/templates/main_app/no_consent_debriefing.html
{% extends "base.html" %}
{% load static %}
{% block cssANDjs %}
    <link rel="stylesheet" href="/static/main_app/stylesheets/no_consent_debriefing.css?{% now "U" %}">
    <script src="/static/main_app/javascript/no_consent_debriefing.js?{% now "U" %}"></script>
{% endblock %}
{% block content %}
    <p>Thank you for your comments. You will be redirected to the homepage in <span class="seconds">10</span> seconds.</p>
{% endblock %}